image:
  name: hashicorp/terraform:1.7.5
  entrypoint: [""]

variables:
  TF_ROOT: .
  TF_STATE_NAME: terraform-state
  TF_ADDRESS: https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}

before_script:
  - terraform init
    -backend-config=address=${TF_ADDRESS}
    -backend-config=lock_address=${TF_ADDRESS}/lock
    -backend-config=unlock_address=${TF_ADDRESS}/lock
    -backend-config=username=gitlab-ci-token
    -backend-config=password=${CI_JOB_TOKEN}

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply tfplan
  when: manual
